### ISSUE TITLE
Chrome GPU

### ISSUE THREAD

**Issue by esetnik** [vit9696/Shiki#13]
Chrome still shows hardware decoding as disabled even though I added a [patch for chrome](https://github.com/esetnik/Shiki/commit/172a2708546a46743167e999f3a0c66f722b6830).

chrome://gpu
```
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
CheckerImaging: Disabled
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Hardware accelerated
Rasterization: Software only, hardware acceleration unavailable
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

It is fixed by adding `#ignore-gpu-blacklist` enabled in `chrome://flags`. I'm not sure if Chrome needs patching but happy to submit a PR if required.

**Comment by vit9696** [comment]
Hi,

I committed the latest source for Lilu, so you could continue your experiments. The issues with chromium (and chrome) come from these lines of code:
https://cs.chromium.org/chromium/src/gpu/config/software_rendering_list.json?type=cs&q=Go5200&l=1016

And the relevant bugreports are:
https://bugs.chromium.org/p/chromium/issues/detail?id=613272
https://bugs.chromium.org/p/chromium/issues/detail?id=614468

This is pretty crazy, and I would say it defeats the purpose of enabling hardware GPU decoding acceleration on chromium. If a whitelist patch (the one you showed) is necessary, I still could accept it but… it hardly feels right to be honest, the user would have to dig deep into the preferences anyway.

**Comment by esetnik** [comment]
Yeah I agree it's a bit crazy. But I get unacceptable rendering performance in chrome without GPU rasterization on 4k monitor. And it seems to work well with 1080TI so I don't know why it's blacklisted / not whitelisted.

I also noticed that electron-based apps do not work. I tried to patch Visual Studio Code and Slack but I still see GPU errors.

For example this is with Slack. Any ideas?
```
❯ /Applications/Slack.app/Contents/MacOS/Slack
GVA info: Successfully connected to the Intel plugin, offline Gen95
AVDCreateGPUAccelerator: Error loading GPU renderer
2017-11-20 14:17:53.151 Slack[11894:919914] Creating Slack Application
...
```

I updated my patch to include electron apps on my system. Not sure if I'm patching them properly. https://github.com/esetnik/Shiki/commit/da1400a88191c22a3f2afbe54d3db58aaff70266

**Comment by vit9696** [comment]
The issue happens when the necessary binary is not patched. I suppose either you did not update/recompile the kext, or electron apps consist of a zillion of binary shitload that need a lot of patching…

**Comment by esetnik** [comment]
Electron apps are working after applying the new changes in https://github.com/vit9696/Shiki/issues/12 without further patching. I'm still seeing performance issues in visual studio code but I think that's a separate issue.

**Comment by vit9696** [comment]
Ok, as for now I committed the PATHs you mentioned in this issue (https://github.com/vit9696/Shiki/commit/64183551cc0fe420e7817e7f1d0e45fec24d69fc).
I guess there is not much more we could do here.

**Comment by esetnik** [comment]
Thanks for that
